### ISSUE TITLE
Event Managers (EPIC)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1803]
Initial stub issue around requirement for more granular authorisation levels for allReady after discussions with @schuback

Event Managers should be able to perform the following actions within the scope of a specific event

- [x] able to view an event
- [ ] able to create tasks - pending new auth classes
- [ ] create itineraries  - pending new auth classes
- [ ] create manual requests - pending new auth classes
- [x] edit event details
- [ ] close out requests - pending new auth classes
- [ ] send messaging to all event volunteers - pending on updated messaging flow
- [ ]  Update event lister / add a new lister page where an event manager can see links to events(s) they have access to manage - Included in #1898
- [ ]  Update menu rules so that anyone with event manager access has an admin menu with a link to the admin event list - Included in #1899

We will need to include a way or storing details of which users are event managers in our database. We will also need to include some changes within our authorisation code to ensure we allow the correct access to manage events for the user's who should have it.

An org admin will invite someone to become an event manager - see #1804

- [ ]  Include a page which will lists all authorized event users - Included in #1900
- [ ]  Add a button with a confirmation screen to allow an org admin (maybe also campaign manager) to revoke event manager access from a user - Included in #1901

**Comment by stevejgordon** [comment]
Working on a PR to enable easier authorization logic to support this "role"

**Comment by stevejgordon** [comment]
We have some of the auth in place now with the AuthorizableEvent code. The controllers / views can start to be hooked up to start enabling the access as defined above.

**Comment by stevejgordon** [comment]
@c0g1t8 As you will be looking at some of the items in here, just let me know if you have any questions around the auth stuff. It's similar to resource based auth but using a custom set of classes to wrap up the code which we need to work out the parent layers for authorization.

**Comment by c0g1t8** [comment]
@stevejgordon Planning to merge PR #1968 locally to get a better perspective.  Is this advisable?

**Comment by tonysurma** [comment]
@c0g1t8 I just merged to master so you no longer need to :)

**Comment by c0g1t8** [comment]
@tonysurma That makes things easier 😄 

@stevejgordon I've done a preliminary review of the latest bits.  I think I understand the pattern you are using.  I'll do a  deeper dive tomorrow.

**Comment by stevejgordon** [comment]
@c0g1t8 If you look at most (not all) of the admin event controller actions you can see examples of how I've used the IAuthorizableEvent bits.

**Comment by c0g1t8** [comment]
@stevejgordon I think I've got it.  Nicely done 😄.  I'm going to work my way through this epic.

It also looks like you'll need to the same with Campaigns.

**Comment by c0g1t8** [comment]
@stevejgordon Below is a screenshot of `http://localhost:48408/Admin/Event/Details/1` while logged in as **eventmanager@example.com**

![image](https://cloud.githubusercontent.com/assets/23250332/25069247/77fd5d42-2230-11e7-9f1c-4adf619fc94e.png)

I believe the **Duplicate** button should not appear since the event manager should not be able to create new events.  Am I correct?

**Comment by stevejgordon** [comment]
@c0g1t8 That's correct. We need to amend the view model to carry a flag whether this should be shown or not and then hide in the view if required.

**Comment by c0g1t8** [comment]
@stevejgordon Done - Including it as part of this issue.

**Update**
I've been working my way through this epic.  Started with _create itineraries_ since I'm most familiar with the `ItineraryController` from working with other issues.  
- Changed the authorize attribute from `[Authorize("OrgAdmin")]` to `[Authorize]`.
- Changed             
```
            if (!User.IsOrganizationAdmin(itinerary.OrganizationId))
            {
                return Unauthorized();
            }
```
 to 
```
            var authorizableEvent = await _mediator.SendAsync(new Features.Events.AuthorizableEventQuery(itinerary.EventId, itinerary.CampaignId, itinerary.OrganizationId));
            if (!await authorizableEvent.UserCanView())
            {
                return new ForbidResult();
            }
```
- Spending quite a bit of time fixing the unit tests

**Questions**
- I'm testing for `authorizableEvent.UserCanView()` for gets and `authorizableEvent.UserCanEdit()` for posts. Is that what you wish?
- Not all the methods have an authorization check.  They appear to be called via javascript.  Not sure if this is a problem.

I'll create a WIP marked PR once I've completed the _Itinerary_ changes for your review.

**Comment by c0g1t8** [comment]
@stevejgordon Just created PR  #1970.  

I went a little off course with the `ItineraryController `🤕.  I originally implemented the authorization for its methods based on `AuthorizableEvent`.  Once I completed my implementation I _rediscovered_ #1787.  It's apparent that the work I did could have/should have used an `AuthorizableItinerary`.  This would provide some uniformity in implementation.  

Is this your plan?  If so, are you planning to provide an implementation for `AuthorizableItinerary`?  Or should I even attempt implementing it based on the `AuthorizableEvent`.

**Comment by c0g1t8** [comment]
@stevejgordon I really should spend more time looking at the commits.  Found your implementation for `AuthorizableItinerary`

**Comment by stevejgordon** [comment]
@c0g1t8 No worries. Yep, for each domain entity (event, itinerary, request) etc there is / will be an IAuthorizableXXX for it which knows how to inspect the User (via the UserAuthorizationService) and establish the access they should have on the entity. Does that make sense?

Sorry, I could have made that more apparent up-front.

**Comment by c0g1t8** [comment]
@stevejgordon 

Looking to finish the work on the `EventController`.  My question regards the `Create` methods.  I'm scratching my head a bit.  To be consistent I would like to be able to use `AuthorizableEventQuery` for determining authorization.  But no valid `EventId` yet exists.

My original plan would be to use the following:
```
    var authorizableEvent = await _mediator.SendAsync(new AuthorizableEventQuery(0, campaign.Id, campaign.OrganizationId));
    if (!await authorizableEvent.UserCanDelete())
    {
        return new ForbidResult();
    }
```

The rationale was that I could check the `UserCanDelete()` method since a user able to _delete_ should be able to _create_.  Passing a the _EventId_ parameter of 0 would indicate that it doesn't exist.  Authorization can be determined based on the Campaign and Organization.

There are a couple of problems with this:
1. Your implementation returns `NotFoundAuthorizableEvent `when the EventId is 0.
2. We don't have a granularity of control on the `Create `method.

My thoughts are to 
1. Add a `UserCanCreate()` method to `IAuthorizable` for clarity.
2. Change the implementation of the `AuthorizableEventBuilder` `Build` method so that passing `0, campaign.Id, campaign.OrganizationId` would check for a valid Campaign and Organisation for authorization.

Did I miss something in your implementation?  Thoughts?

**Comment by stevejgordon** [comment]
My thoughts on event creation  were that we would uae the authorizable campaign to then validate against it's manage child method.

**Comment by c0g1t8** [comment]
@stevejgordon Okay - that works for me.

**Comment by c0g1t8** [comment]
@stevejgordon I just updated the PR #1970.
- added `AuthorizableCampaignQuery` to match `AuthorizableEventQuery` with a matching **Handler**
- added `FakeAuthorizableCampaign` for use in testing an made it public
- extracted `FakeAuthorizableEvent` to make it public
- updated `EventController` Create methods

Thoughts?

**Comment by c0g1t8** [comment]
I want to provide more information on PR #19- 70 and update this issue.  This PR enables
> able to create tasks - pending new auth classes
create itineraries - pending new auth classes
create manual requests - pending new auth classes
close out requests - pending new auth classes

In the sample data a user **eventmanager@example.com** is already assigned as an _Event Manager_ to an event.  It can be directly accessed - http://localhost:48408/admin/event/Details/1` when logged in as the _Event Manager_.

@stevegordon - Can we update your initial issue report above to reflect this?

**Comment by stevejgordon** [comment]
@c0g1t8 Updated, thanks.
