### ISSUE TITLE
Public Request Creation for Events (EPIC)

### ISSUE THREAD

**Issue by stevejgordon** [HTBox/allReady#1830]
Related to discussions in #1241

We need to allow for public visitors to allReady to register an interest (add a request) for events that support requests.

This is a placeholder for now. I will spend some time fleshing this out more deeply before work begins.

**Comment by stevejgordon** [comment]
Initial thoughts (WIP). Once confirmed and finalised I will break these out into specific issues so that work can begin.

- [ ] Add flag to campaign to enable/disable allReady request creation (non logged in users) as this is a feature that we may not require on all campaigns.
- [ ] Add a status or flag on requests that identity the source - we may want to treat this as un-validated for example.
- [ ] Add a page that allows non registered users to make a request against a campaign (default fields).
- [ ] Consider the possibility that we need to extend requests to accept additional campaign specific questions / data.
