### ISSUE TITLE
Data Reporting - EPIC

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2016]
**Summary**: The event manager is where you can see all of the events that are scheduled. We need to have an overview of seeing all of the possible data that can be mined from the events manager.

**What we want:** As an end user i want an easy to use dashboard for seeing all of the data that has been entered in the events manager, have the ability to create reports from this information and have it exportable to be able to report this to key stakeholders.

- [ ] We need to have a list of all the fields that are available for use in reports. This list can be provided in excel or another user friendly format (i.e. not a txt file). (see #2017) - Once this list is provided there will be further breakdowns of required reports by Pascal and Jim

- [ ] Initial fields that should be in the portal are:
-  how many volunteers in total were in a specific day (there should be a date range available in calendar format)
- how many hours were spent in total
- time tracking per volunteer
- human asset tracking
- how many smoke detectors were handed out in a specific day
- age of volunteers 
- gender
- age

- [ ] We need to have a dashboard built within the portal that would allow reports to be created and exported in .csv,.xls, .pdf.

**Comment by MisterJames** [comment]
This is a great start of some of the required info we will need to build out the requisite data for reports.

I want to make sure that we don't fall into the trap of "reports from fields in tables", though, so we will instead build the report data from the eventing system that we already report. Said another way, we want events that occur to create data specific to an exact report. 

I would like to loop in @dpaquette to discuss some of this on the technical side (if he has time), but we can definitely move forward with clarifications and requirements. 

I'll get a list of all the fields we're currently tracking across tables; that will allow us to progress this conversation in the interim. 

Thanks @EmilyLuijbregts!

**Comment by EmilyLuijbregts** [comment]
Thanks @MisterJames! I know that @stevejgordon was also working through some requirements. Please let me know if you've got any questions and I'll coordinate with @OhMcGoo and @Schuback

**Comment by stevejgordon** [comment]
@MisterJames I'm thinking we should start recording events (some kind of basic event store) somewhere and then use those to build report views. Using a full-blown event store model might be quite heavy for now, but perhaps we could define an event table and store json messages in there that allow us to play through and read data into views either on demand or via tasks?

@EmilyLuijbregts - I probably have questions about each report as we get there but let's start with:

> how many volunteers in total were in a specific day (there should be a date range available in calendar format)

So I interpret this as: we'd like to see per day (for a given date range) then number of volunteers across all tasks/requests in an event?

i.e.

Date             |  Volunteers
2017-08-11  |  08
2017-08-10  |  10

Something to consider is how we generate the data. At the moment we have the possibility of data (source of truth) changing. ie. on the day of an event a volunteer could have been assigned to it and maybe participated. However, for some reason, the day after they are removed (more likely in longer running events). The possibilities for this to occur might be suite slim but I think are worth considering.

In that case, currently, at the time of running a report it's possible the lookup from the database (which would no longer include that user against the event) could reflect invalid data for those dates they did help.

I think storing user assignment type events might allow us to compile a more accurate data set. Possibly with a scheduled task to update such data daily. 

Final question for now. Do we have a view of how we want to represent this in the UI. Is this going to be tabular data that can be exported or are we also wanting to include graphs?
