### ISSUE TITLE
Maps - EPIC

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2021]
**Summary**: The maps feature is where you're able to see all of the events in a specific location and area. 

**What we want:** As an end user i want an easy to use map functionality that will allow me to have an overview of all of the events in a specific area, be able to zoom in and out and have this automatically adjusted if there are updates to the status of any of the events in that map so that we can dynamically see any changes that are made.

This is broken down into the following areas:

- [ ] The map layout should show all events over one campaign or one calendar day
- [ ] The map layout should have the option of choosing between the relevant campaign and / or calendar day.
- [ ] Able to add/duplicate tasks to existing pins on the maps
- [ ] When hovering over a pin, you should be able to see all of the tasks listed under this pin
- [ ] You should be able to update a pin from the map/pin and without having to open the pin itself
- [ ] You should be able to do multiple updates from the map overview 
- [ ] The map and system need to be automatically updated and adjusted if a 'decline' comes in.

Will be added at a later time:

- [ ] Map should be able to look at the pins and provide a ‘logical’ list for the groups of volunteers (“Itinerary Builder”) 
- [ ] There should be the ability to have multiple options/layout on the map feature. [DEFINITION IN PROGRESS]
- [ ] Map overview for volunteers showing different views (e.g. start/end time) [DEFINITION IN PROGRESS]

**Comment by stevejgordon** [comment]
@OhMcGoo @EmilyLuijbregts - We have a map at itinerary level which is used for managing that specific itinerary. Can I confirm that this issue is intended to function at a higher level and looks to show information for a full campaign on a map?

I'll probably have some more specific questions for some of the breakdown items too.

// cc @tonysurma

**Comment by OhMcGoo** [comment]
@stevejgordon, @EmilyLuijbregts: Initially, I think we should have one map view (page) that can be used to both create itineraries and see a larger overview of pending, scheduled, declined and fulfilled requests. I'm not sure I understand the following features and suggest, perhaps, a quick Skype call to clarify:

- Able to add/duplicate tasks to existing pins on the maps
- When hovering over a pin, you should be able to see all of the tasks listed under this pin
- You should be able to update a pin from the map/pin and without having to open the pin itself
- You should be able to do multiple updates from the map overview
- The map and system need to be automatically updated and adjusted if a 'decline' comes in.

**Comment by EmilyLuijbregts** [comment]
Thanks for answering and clarifying @OhMcGoo !

**Comment by MisterJames** [comment]
@EmilyLuijbregts and @OhMcGoo we can add this epic (and related tasks) to our stakeholders meeting. Thanks all!
