### ISSUE TITLE
Events - EPIC

### ISSUE THREAD

**Issue by EmilyLuijbregts** [HTBox/allReady#2039]
**Summary**: We need to update the Events feature on the website to make it more accessible and user friendly to the users

**What we want:** As an end user I want to have an easy to use Events feature that will enable me to be more efficient when entering/amending events. 

This is broken out into the following issues:

- [ ] Ability to create an event as a Campaign Manager
- [ ] Ability to take requests from third party (getasmokealarm.org) and transfer them into tasks/assignments
- [ ] Ability to add information to a task 
- [ ] Creation of event should have a list of pre-required fields to be checked by the corrector
- [ ] There should be the ability to have communication between the requesters and volunteers for a series of actions.
- [ ] Tasks should be able to be duplicated/added/deleted
- [ ] Volunteers are able to sign up for events and different tasks
- [ ] Admin’s can assign volunteers to tasks
- [ ] Admins can remove volunteers from assignments and tasks
- [ ] Volunteers should be able to see all possible events and tasks
- [ ] Role based permissions for admin/volunteer 
- [ ] Volunteer should be able to select the events that they want to do and subscribe to updates
- [ ] Need to be able to filter requests into date range and see the different requests available
- [ ] Update to state events
- [ ] Safety message page creation as a sub page from an event
