### ISSUE TITLE
5.1.1.3.4	Organization admins can create campaigns with landing page content

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#35]
This feature incorporates a number of tasks:
 - [x] Basic model: Name, Description [Rich Text Multi Paragraph with images etc.], Campaign contact info, links to campaign web pages
 - [ ] #246 simplify Logo/Image upload
 - [ ] #247 create keyword container/UI (some kind tag library)
 - [ ] #248 Geography Coverage (zipcode list, city list, state list) be able to select neighborhoods or define a boundary with zip codes or city or state
 - [x] #249 Add button to populate contact info from org
 - [x] #250 Add thermometer rendering based on current and target values

**Previous Copy**
_including but not limited to: Name, Logo/Image, Description [Rich Text Multi Paragraph with images etc.], Keywords, Geography Coverage (zipcode list, city list, state list), Campaign contact info (allow copy from organization but this may be different per campaign), links to campaign web pages, impact target {‘x’ ‘things’ by ‘y’ date} and list of interim goals in either format of {‘z’ ‘things’ per ‘week/month/quarter’} or {‘z’ ‘things’ by ‘y’ date, ‘z1’ ‘things by ‘y1’ date, …} or {‘textual goal’} the last format of which will not be trackable by the system and will be marked as completed by the admin_

**Comment by joelhulen** [comment]
I'll take this one on.

Might be good to take a few minutes to discuss some of the finer details.

**Comment by joelhulen** [comment]
Could you please clarify some things:

1. Geography coverage
    * Do we want to focus on US states right now, or global?
    * If US only for now, I assume we want to capture the country code for future expandability
2. Campaign web pages
    * Are these links to external pages?
    * If not, is there an area within allReady that makes up the campaign web pages?
3. Would like to flesh out the impact targets and interim goals
    * When you say 'trackable', what are you wanting to track, exactly? Depending on how granular you want the tracking, we may need to break these items down to separate entities. Or, is it simply a bit field that indicates whether a target was hit?
    * What is the hierarchy of impact targets to interim goals? Is one a child of another, or are they siblings?

**Comment by tonysurma** [comment]
Some initial notes and I will add more in a few
1) US only and country code for expansion would be good
2) the goal is for the campaign entity to have all the information above so it can be displayed on the campaign 'landing page' which right now is just a view with like the name and dates.  One of the items is links to external pages so that they can have a click over to a page on their website.  We do want a campaign to have content like a little rich text section etc so a campaign can exist without an external web page
3) I would focus less on this for now and as we build out the volunteer activity work we can flesh this out.  That being said the goal is for an organization to say something like (totally fake) 'deliver 1000 pizzas by December 2016' and then be able to update their progress over time (go in tomorrow and say they delivered 20, then next month say 100, and so on until they go on in December or earlier and say they did 1000 or however many and make the goal) So think of it as a number goal at a data and entries for each time they have updated progess (kinda like those thermometer views you see when someone is trying to raise 10K for whatever charity and they move the red part higher as they earn more).  The advanced case would be for them to say 1000 by Dec 2016, 500 by July 2016, 125 by Dec 2015 or whatever so as the enter progress we can show/benchmark that against goals.

Hope this helps and again I will add more later

**Comment by joelhulen** [comment]
Thanks for the clarification.

As per point #3, it almost sounds like milestones with an integer for the stated goal, and related data with an integer for denoting progress. Do you foresee a case where the goal would not be numeric, but perhaps a boolean or some other data type instead? I'm excluding text from this scenario since that's already been listed as a simplified goal.

**Comment by tonysurma** [comment]
that could be a case but I think integral progress would be a good focus for now.  Thanks @joelhulen

**Comment by joelhulen** [comment]
I am working on the campaign landing page, and have added a "Full Description" WYSIWYG field. One of the feature requests is to have images as part of this content. Out of the box, WYSIWYG controls such as TinyMCE insert images in the form of a URI to the image path somewhere on the internet. Does this satisfy the scope of this requirement, or should we add a way for the end user to upload one or more images? This starts taking us down the path of creating an image manager (if you're going to have more than one image), having images shown that only the logged in user has uploaded, etc.

Just trying to figure out if it's worth opening this can of worms at this stage?

**Comment by joelhulen** [comment]
As I dig deeper into campaigns and their associated activities, I see where locations come into play IRT geography coverage. Currently, only activities have locations. Since activities are assigned to campaigns, the only location data for a campaign are inferred by the location(s) of its activity(ies).

Do we want to now specify a location or range of locations for a campaign? If so, to what end? For instance, searching takes into account locations of activities by zip code. It can be argued that more location-based search options can be incorporated to include points on a map and shapes. If location for a campaign is defined by its activities, what would be the purpose of defining a location for the campaign? Please clarify this particular requirement.

**Comment by tonysurma** [comment]
@joelhulen : (re: images) Adding in links to existing uri's for images is good for now.  We don't need to do image mgmt now and later we may do that from something/where else anyways as we probably want them via cdn etc. anyways

@joelhulen : (re: locations) activities typically have specific points ('hand out flyers during the blah blah event at Clark and Lasalle in Chicago') campaigns are focused on geographic boundaries which can be political (city, county, state, etc.), groups of zipcodes, or informal (like 'near north side', 'northern Naperville', etc.)

I would think for now if we can do zipcodes and/or political that would be enough and hopefully lack complexity like the informal entries or even 'draw a polygon on a map' type answers.  Thoughts?

**Comment by joelhulen** [comment]
Thanks for the clarification, @tonysurma.

For the campaign location, I think it would be best to use SQL Spatial types to identify geographical boundaries in the form of multiple zip codes (union), or political (city, county, state, etc.). I assume that the location serves two primary purposes (please correct me if I'm wrong): Informational and discoverability from searching by the user's zip code.

That said, you wouldn't be able to search by informal. I suppose you could offer informal as an option whereby it is excluded from searches as well as map displays.

**Comment by tonysurma** [comment]
@joelhulen @MisterJames I am going to mark this closed.  Please create any issues and reference back if you believe there is something still open but not covered by one of the sub issues up above
