### ISSUE TITLE
Event searching and viewing enhancements

### ISSUE THREAD

**Issue by cecilia-donnelly** [HTBox/allReady#373]
It would be nice to have a page called "my events" that shows what the logged-in user has already volunteered for.  Similarly, maybe the app could show a calendar of all events so that users can search for events by date instead of just by zipcode.  These could even be the same calendar page, and users could filter by "events I've signed up for," "events near me," and "all events."

This is probably something more for 2.0, but when I was clicking around in the app I thought it would be useful.

Possibly labels: "enhancement," "volunteer workflow" 

---

Tracking this with the following:
- [ ] #376 Create "My Events" Page For Volunteers
- [ ] #377 Create a Calendar of Events
- [ ] #378 Allow Calendar of Events to By Filtered by Logged in User

**Comment by tonysurma** [comment]
Great points and was thinking similar.  We will likely break down to multiple tasks when we get to working on it.

**Comment by MisterJames** [comment]
I'm splitting this down into other tasks now.

**Comment by tonysurma** [comment]
Thank you @MisterJames

**Comment by stevejgordon** [comment]
Closing as the initial iteration of this is in place. UX review and enhancements can follow as new issues,
