### ISSUE TITLE
Add "ActivityType" property to "Activity" model to support new Activity workflows

### ISSUE THREAD

**Issue by mmoore99** [HTBox/allReady#505]
This is a sub issue from #504 

- [ ] Add "ActivityTypes" enum with entries for the different activity types (ActivityManaged, TaskManaged, DeploymentManaged).  Note that per @tonysurma in #504 these names may be changed.
- [ ] Add "ActivityType" property to "Activity" model
- [ ] Create database migration script
- [ ] Add "ActivityType" to  admin add/edit dialog for Activity 

The following will be handled in other sub-issues:
- [ ] Verify admin assignment flows for new activity type (see #506, #507, #508)
- [ ] Schedule reminder communication (Issue not yet created)
- [ ] Generate link for "no longer able to volunteer" (see #512)

**Comment by MisterJames** [comment]
Each one of those checkpoints will be a separate PR but not necessarily a seperate issue, so they may need a little more detail.

**Comment by mmoore99** [comment]
@MisterJames thanks for the feedback.  

My thought process was to have this specific issue be narrowly focused on just the tasks required to getting the "ActivityType" property in the system and available to be used.  Tasks like "Verify admin assignment flows for new activity type"  and "Create endpoint for above link to accept volunteer cancellation" would be included in the detail issue for each specific activity workflow (see #506 as an example).  Let me now what you think.

> So those last three points I added maybe need to be moved out to a separate task so that a proper service can be built around that.

I agree that there should be a separate issue for the email tokens and "magic" logins.

Regarding, the scheduling of reminder emails, should there be a new issue created or would this fall under #258?

**Comment by mmoore99** [comment]
@MisterJames I have PR ready that implements the following:

- [x] Add "ActivityTypes" enum with entries for the different activity types (ActivityManaged, TaskManaged, DeploymentManaged).  Note that per @tonysurma in #504 these names may be changed.
- [x] Add "ActivityType" property to "Activity" model
- [x] Create database migration script
- [x] Add "ActivityType" to  admin add/edit dialog for Activity 

Do you want to create a feature branch to receive the PR's that will be associated with these new activity workflows?

**Comment by mmoore99** [comment]
Submitted PR #514
