### ISSUE TITLE
6.1.1	Featured Campaign and External Link Capability

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#694]
Highest priority new requirement for "Go Live" release.  Sub Issues are separated out as below:
- [x] #689  6.1.1.1 Feature single campaign on front page of app – P1
- [x] #690  6.1.1.2 Remove/hide search functionality – P1
- [x] #691  6.1.1.3 Display link to list of campaigns on home page – P2
- [x] #692  6.1.1.4 Add external link and highlight it on campaign display page – P1
- [x] #693  6.1.1.5 Enhance UX of campaign display and interaction page – P2
- [x] #769  6.1.1.6     Modify Campaign to allow setting the Featured flag from UI - P1

**Comment by tonysurma** [comment]
closing this larger issue as only one sub item is open and is in discussion
