### ISSUE TITLE
6.1.3	Data Integration with getasmokealarm.org (pull data)

### ISSUE THREAD

**Issue by MKSessions** [HTBox/allReady#700]
Sub issues are separated out as below:
- [x]  #701  6.1.3.1 Implement a webjob/service to pull incremental net new requests from getasmokealarm.org 
- [x]  #702 6.1.3.2 Maintain database of requests
- [x]  #703 6.1.3.3 Update statuses as part of delivery of service for requests as per functionality in 6.1.4
- [x]  #704 6.1.3.4 Allow viewing of status by requestor (lowest priority) (this has been broken out into #1585)

**Comment by MKSessions** [comment]
Sub issues are separated out as below:

[] #701  6.1.3.1 Implement a webjob/service to pull incremental net new requests from getasmokealarm.org 
[] #702 6.1.3.2 Maintain database of requests
[] #703 6.1.3.3 Update statuses as part of delivery of service for requests as per functionality in 6.1.4
[] #704 6.1.3.4 Allow viewing of status by requestor (lowest priority)

**Comment by tonysurma** [comment]
@mgmccarthy we now have sub items

**Comment by tonysurma** [comment]
For all of these this applies:

Here is the link to the [repo for getasmokealarm.org](https://github.com/redcross/smoke-alarm-portal)

I have email into a contact there provided by @OhMcGoo to start the discussion and will get them connected to this issue

**Comment by mgmccarthy** [comment]
@tonysurma, do you see these sub tasks above being broken out to different developers?

**Comment by tonysurma** [comment]
Yes, with communication been them in turn but yes

**Comment by MisterJames** [comment]
@mgmccarthy As we get further along here I'll break out some tasks that can be picked up by the wider cast. Thanks!

**Comment by mgmccarthy** [comment]
@MisterJames, thanks. I saw you were taking the lead on this. Please feel free to delegate anything you need to me where i can help.

**Comment by tonysurma** [comment]
@mgmccarthy again think this is broken out in other issues and can be closed, agree?

**Comment by mgmccarthy** [comment]
@tonysurma I checked off the items in the original list at the top of the Issue that are now done.

as far as this line item:
- #703 6.1.3.3 Update statuses as part of delivery of service for requests as per functionality in 6.1.4

I'm not too sure what it means. We don't accept incoming status updates from GASA anymore, we only accept "new" status Requests from them
