### ISSUE TITLE
6.1.2	Register Volunteers for Itinerary Type Campaigns

### ISSUE THREAD

**Issue by tonysurma** [HTBox/allReady#709]
- [x] #705 6.1.2.1  Entities have new names from user experience discussions – P2
- [x] #706 6.1.2.2  Entity Relationships and definitions have (possibly) shifted a bit – P1
- [x] #707 6.1.2.3  Itinerary Campaigns are the new name/functionality for Deployment Managed Tasks – P1
- [x] #708 6.1.2.4  Events can be duplicated easily to allow for campaigns that consist of repetitive tasks

**Comment by stevejgordon** [comment]
@tonysurma I believe these higher level requirements are now all met in the features we have.

**Comment by stevejgordon** [comment]
@tonysurma - Do you think this can be closed or are there items left I can break out for next week?

**Comment by tonysurma** [comment]
@stevejgordon if #706 can be closed then this can be closed
